name: Test Reusable Workflow

permissions:
  contents: write
  pages: write
  deployments: write

on:
  workflow_dispatch:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  deploy:
    uses: roshansamantaray/test-repo/.github/workflows/gh-pages.yml@main
    with:
      deploy_branch: ${{ github.ref_name }}
      version: "1.2.3"  # You can test passing a custom version
      version_source: "gradle"