name: Test Branch Snapshot Deployment

permissions:
  contents: write
  pages: write
  deployments: write

on:
  workflow_dispatch:
    push:
      branches:
        - develop
        - release/*

jobs:
  deploy-snapshot:
    uses: roshansamantaray/test-repo/.github/workflows/pages-branch-snapshot.yml@main
    with:
      deploy_branch: ${{ github.ref_name }}
      version: "maven"
