name: Test Reusable Workflow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  deploy:
    uses: secure-software-engineering/actions/.github/workflows/gh-pages.yml@develop
    with:
      deploy_branch: ${{ github.ref_name }}
      version: "1.2.3"  # You can test passing a custom version