name: Test PR Preview Deployment

permissions:
  contents: write
  pages: write
  deployments: write

on:
  workflow_dispatch:
    pull_request:
      types: [ opened, synchronize, reopened, closed ]


jobs:
  deploy-pr-preview:
    uses: roshansamantaray/test-repo/.github/workflows/pages-pr-review.yml@main
    with:
      enable_comment: true
