name: Test PR Preview Deployment

on:
  workflow_dispatch:
    pull_request:
      types: [ opened, synchronize, reopened, closed ]


jobs:
  deploy-pr-preview:
    uses: roshansamantaray/test-repo/.github/workflows/pages-pr-review.yml@main
    with:
      enable_comment: true
